services:
  - type: web
    name: devcortex-ai
    env: go
    buildCommand: go mod tidy && go build -o app ./cmd/web
    startCommand: ./app
    plan: free
    envVars:
      - key: PORT
        value: 80
