package handler

import (
	"net/http"
)

func RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/", Home)
	mux.HandleFunc("/tools", Tools)

	mux.HandleFunc("/tools/regex-deconstructor", RegexTool)
	mux.HandleFunc("/tools/sql-autopsy", SQLAutopsyTool)
	mux.HandleFunc("/tools/sql-performance", SQLPerformanceTool)
	mux.HandleFunc("/tools/base64", Base64Tool)
	mux.HandleFunc("/tools/jwt-decoder", JWTTool)
	mux.HandleFunc("/tools/hash-generator", HashTool)
	mux.HandleFunc("/tools/timestamp-converter", TimestampTool)
	mux.HandleFunc("/tools/json-formatter", JSONTool)
	mux.HandleFunc("/tools/json-to-code", JsonToCode)
	mux.HandleFunc("/tools/uuid-generator", UUIDTool)
	mux.HandleFunc("/tools/regex-tester", RegexTool)
	mux.HandleFunc("/tools/color-picker", ColorPickerTool)
	mux.HandleFunc("/tools/lorem-ipsum", LoremIpsumTool)
	mux.HandleFunc("/tools/url-encoder", URLEncoderTool)
	mux.HandleFunc("/tools/case-converter", CaseConverterTool)
	mux.HandleFunc("/tools/minifier", MinifierTool)
	mux.HandleFunc("/tools/markdown-previewer", MarkdownPreviewerTool)
	mux.HandleFunc("/tools/diff-checker", DiffCheckerTool)
	mux.HandleFunc("/tools/random-string", RandomStringTool)
	mux.HandleFunc("/tools/cron-explainer", CronTool)

	// Coming Soon Routes
	mux.HandleFunc("/tools/token-generator", TokenGeneratorTool)
	mux.HandleFunc("/tools/bcrypt-hash", BcryptTool)
	mux.HandleFunc("/tools/encrypt-decrypt", EncryptDecryptTool)
	mux.HandleFunc("/tools/bip39-generator", Bip39GeneratorTool)
	mux.HandleFunc("/tools/hmac-generator", HMACGeneratorTool)
	mux.HandleFunc("/tools/rsa-generator", RSAGeneratorTool)
	mux.HandleFunc("/tools/password-strength", PasswordStrengthTool)
	mux.HandleFunc("/tools/pdf-signature-checker", ComingSoon)
	mux.HandleFunc("/tools/ulid-generator", ULIDGeneratorTool)
	mux.HandleFunc("/tools/favicon-generator", FaviconGeneratorTool)
	mux.HandleFunc("/tools/qr-code-generator", QRCodeGeneratorTool)
	mux.HandleFunc("/tools/image-converter", ImageConverterTool)
	mux.HandleFunc("/tools/svg-optimizer", SVGOptimizerTool)
	mux.HandleFunc("/tools/yaml-to-json", YAMLToJSONTool)
	mux.HandleFunc("/tools/json-to-xml", JSONToXMLTool)
	mux.HandleFunc("/tools/json-to-csv", JSONToCSVTool)
	mux.HandleFunc("/tools/json-to-toml", JSONToTOMLTool)
	mux.HandleFunc("/tools/yaml-to-toml", YAMLToTOMLTool)
	mux.HandleFunc("/tools/html-formatter", HTMLFormatterTool)
	mux.HandleFunc("/tools/js-formatter", JSFormatterTool)
	mux.HandleFunc("/tools/css-formatter", CSSFormatterTool)
	mux.HandleFunc("/tools/crontab-generator", CronTool)
	mux.HandleFunc("/tools/color-converter", ColorConverterTool)
	mux.HandleFunc("/tools/curl-builder", CURLBuilderTool)
	mux.HandleFunc("/tools/text-stats", TextStatsTool)
	mux.HandleFunc("/tools/datetime-converter", TimestampTool)
	mux.HandleFunc("/tools/url-decoder", URLEncoderTool)
	mux.HandleFunc("/tools/git-cheatsheet", GitCheatsheetTool)
	mux.HandleFunc("/tools/linux-cheatsheet", LinuxCheatsheetTool)
	mux.HandleFunc("/tools/regex-cheatsheet", RegexCheatsheetTool)
	mux.HandleFunc("/tools/docker-cheatsheet", DockerCheatsheetTool)
	mux.HandleFunc("/tools/kubernetes-cheatsheet", KubernetesCheatsheetTool)
	mux.HandleFunc("/tools/ffmpeg-cheatsheet", FFmpegCheatsheetTool)
	mux.HandleFunc("/tools/ssh-cheatsheet", SSHCheatsheetTool)
	mux.HandleFunc("/tools/find-cheatsheet", FindCheatsheetTool)
	mux.HandleFunc("/tools/nginx-cheatsheet", NginxCheatsheetTool)
	mux.HandleFunc("/tools/http-status-codes", HTTPStatusCodesCheatsheetTool)
	mux.HandleFunc("/tools/mime-types-cheatsheet", MimeTypesCheatsheetTool)
	mux.HandleFunc("/tools/vim-cheatsheet", VimCheatsheetTool)
	mux.HandleFunc("/tools/curl-cheatsheet", CurlCheatsheetTool)
	mux.HandleFunc("/tools/sql-cheatsheet", SQLCheatsheetTool)
	mux.HandleFunc("/tools/net-cheatsheet", NetCommandsCheatsheetTool)
}
