package handler

import (
	"net/http"
)

func RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/", Home)
	mux.HandleFunc("/tools", Tools)

	mux.HandleFunc("/tools/regex-deconstructor", RegexTool)
	mux.HandleFunc("/tools/sql-autopsy", SQLAutopsyTool)
	mux.HandleFunc("/tools/sql-performance", SQLPerformanceTool)
	mux.HandleFunc("/tools/base64", Base64Tool)
	mux.HandleFunc("/tools/jwt-decoder", JWTTool)
	mux.HandleFunc("/tools/hash-generator", HashTool)
	mux.HandleFunc("/tools/timestamp-converter", TimestampTool)
	mux.HandleFunc("/tools/json-formatter", JSONTool)
	mux.HandleFunc("/tools/json-to-code", JsonToCode)
	mux.HandleFunc("/tools/uuid-generator", UUIDTool)
	mux.HandleFunc("/tools/regex-tester", RegexTool)
	mux.HandleFunc("/tools/color-picker", ColorPickerTool)
	mux.HandleFunc("/tools/lorem-ipsum", LoremIpsumTool)
	mux.HandleFunc("/tools/url-encoder", URLEncoderTool)
	mux.HandleFunc("/tools/case-converter", CaseConverterTool)
	mux.HandleFunc("/tools/minifier", MinifierTool)
	mux.HandleFunc("/tools/markdown-previewer", MarkdownPreviewerTool)
	mux.HandleFunc("/tools/diff-checker", DiffCheckerTool)
	mux.HandleFunc("/tools/random-string", RandomStringTool)
	mux.HandleFunc("/tools/cron-explainer", CronTool)

	// Coming Soon Routes
	mux.HandleFunc("/tools/token-generator", TokenGeneratorTool)
	mux.HandleFunc("/tools/bcrypt-hash", BcryptTool)
	mux.HandleFunc("/tools/encrypt-decrypt", ComingSoon)
	mux.HandleFunc("/tools/bip39-generator", ComingSoon)
	mux.HandleFunc("/tools/hmac-generator", ComingSoon)
	mux.HandleFunc("/tools/rsa-generator", ComingSoon)
	mux.HandleFunc("/tools/password-strength", ComingSoon)
	mux.HandleFunc("/tools/pdf-signature-checker", ComingSoon)
	mux.HandleFunc("/tools/ulid-generator", ComingSoon)
	mux.HandleFunc("/tools/favicon-generator", ComingSoon)
	mux.HandleFunc("/tools/qr-code-generator", ComingSoon)
	mux.HandleFunc("/tools/image-converter", ComingSoon)
	mux.HandleFunc("/tools/svg-optimizer", ComingSoon)
	mux.HandleFunc("/tools/gif-compressor", ComingSoon)
	mux.HandleFunc("/tools/image-compressor", ComingSoon)
	mux.HandleFunc("/tools/yaml-to-json", ComingSoon)
	mux.HandleFunc("/tools/json-to-xml", ComingSoon)
	mux.HandleFunc("/tools/json-to-csv", ComingSoon)
	mux.HandleFunc("/tools/json-to-toml", ComingSoon)
	mux.HandleFunc("/tools/yaml-to-toml", ComingSoon)
	mux.HandleFunc("/tools/markdown-to-word", ComingSoon)
	mux.HandleFunc("/tools/markdown-to-pdf", ComingSoon)
	mux.HandleFunc("/tools/html-formatter", ComingSoon)
	mux.HandleFunc("/tools/js-formatter", ComingSoon)
	mux.HandleFunc("/tools/sql-formatter", ComingSoon)
	mux.HandleFunc("/tools/css-formatter", ComingSoon)
	mux.HandleFunc("/tools/crontab-generator", ComingSoon)
	mux.HandleFunc("/tools/color-converter", ComingSoon)
	mux.HandleFunc("/tools/curl-builder", ComingSoon)
	mux.HandleFunc("/tools/text-stats", ComingSoon)
	mux.HandleFunc("/tools/datetime-converter", ComingSoon)
	mux.HandleFunc("/tools/url-decoder", ComingSoon)
	mux.HandleFunc("/tools/git-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/linux-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/regex-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/docker-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/kubernetes-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/ffmpeg-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/ssh-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/find-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/nginx-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/http-status-codes", ComingSoon)
	mux.HandleFunc("/tools/mime-types-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/vim-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/curl-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/sql-cheatsheet", ComingSoon)
	mux.HandleFunc("/tools/net-cheatsheet", ComingSoon)
}
