package model

type Tool struct {
	Name        string
	Description string
	URL         string
	Icon        string
	Category    string
}

var FeaturedTools = []Tool{
	{
		Name:        "SQL Performance Analyzer",
		Description: "Analyze SQL query execution plans and get performance recommendations.",
		URL:         "/tools/sql-performance",
		Icon:        "bi bi-activity",
		Category:    "featured",
	},
	{
		Name:        "Cron Explainer",
		Description: "Analyze, visualize, and debug cron expressions.",
		URL:         "/tools/cron-explainer",
		Icon:        "bi bi-calendar-event",
		Category:    "featured",
	},
	{
		Name:        "Regex Deconstructor",
		Description: "Visualize, learn, and optimize regex expressions.",
		URL:         "/tools/regex-deconstructor",
		Icon:        "bi bi-braces-asterisk",
		Category:    "featured",
	},
}

var OtherTools = []Tool{
	{
		Name:        "JSON Formatter",
		Description: "Format and validate JSON data.",
		URL:         "/tools/json-formatter",
		Icon:        "bi bi-braces",
		Category:    "other",
	},
	{
		Name:        "JSON to Code",
		Description: "Convert JSON data to your selected programming language.",
		URL:         "/tools/json-to-code",
		Icon:        "bi bi-file-code",
		Category:    "other",
	},
	{
		Name:        "Token Generator",
		Description: "Generate secure tokens.",
		URL:         "/tools/token-generator",
		Icon:        "bi bi-key",
		Category:    "other",
	},
	{
		Name:        "Bcrypt Hash & Compare",
		Description: "Hash and compare passwords with Bcrypt.",
		URL:         "/tools/bcrypt-hash",
		Icon:        "bi bi-shield-lock",
		Category:    "other",
	},
	{
		Name:        "Encrypt/Decrypt Text",
		Description: "Encrypt and decrypt text with AES.",
		URL:         "/tools/encrypt-decrypt",
		Icon:        "bi bi-lock",
		Category:    "other",
	},
	{
		Name:        "BIP39 Passphrase Generator",
		Description: "Generate BIP39 mnemonic passphrases.",
		URL:         "/tools/bip39-generator",
		Icon:        "bi bi-wallet2",
		Category:    "other",
	},
	{
		Name:        "HMAC Generator",
		Description: "Generate HMAC hashes.",
		URL:         "/tools/hmac-generator",
		Icon:        "bi bi-hash",
		Category:    "other",
	},
	{
		Name:        "RSA Key Pair Generator",
		Description: "Generate public/private RSA key pairs.",
		URL:         "/tools/rsa-generator",
		Icon:        "bi bi-diagram-2",
		Category:    "other",
	},
	{
		Name:        "Password Strength Analyser",
		Description: "Analyze the strength of your password.",
		URL:         "/tools/password-strength",
		Icon:        "bi bi-bar-chart",
		Category:    "other",
	},
	{
		Name:        "PDF Signature Checker",
		Description: "Check for digital signatures in PDF files.",
		URL:         "/tools/pdf-signature-checker",
		Icon:        "bi bi-file-earmark-check",
		Category:    "other",
	},
	{
		Name:        "ULID Generator",
		Description: "Generate ULIDs.",
		URL:         "/tools/ulid-generator",
		Icon:        "bi bi-123",
		Category:    "other",
	},
	{
		Name:        "Favicon Generator",
		Description: "Create favicons from images.",
		URL:         "/tools/favicon-generator",
		Icon:        "bi bi-gem",
		Category:    "other",
	},
	{
		Name:        "QR Code Generator",
		Description: "Generate QR codes from text or URLs.",
		URL:         "/tools/qr-code-generator",
		Icon:        "bi bi-qr-code",
		Category:    "other",
	},
	{
		Name:        "Image Converter",
		Description: "Convert images between formats (PNG, JPG, WebP).",
		URL:         "/tools/image-converter",
		Icon:        "bi bi-image-alt",
		Category:    "other",
	},
	{
		Name:        "SVG Optimizer",
		Description: "Optimize SVG files for the web.",
		URL:         "/tools/svg-optimizer",
		Icon:        "bi bi-vector-pen",
		Category:    "other",
	},
	{
		Name:        "GIF Compressor",
		Description: "Compress animated GIF files.",
		URL:         "/tools/gif-compressor",
		Icon:        "bi bi-film",
		Category:    "other",
	},
	{
		Name:        "Image Compressor",
		Description: "Compress JPG and PNG images.",
		URL:         "/tools/image-compressor",
		Icon:        "bi bi-aspect-ratio",
		Category:    "other",
	},
	{
		Name:        "YAML to JSON Converter",
		Description: "Convert YAML data to JSON.",
		URL:         "/tools/yaml-to-json",
		Icon:        "bi bi-file-earmark-code",
		Category:    "other",
	},
	{
		Name:        "JSON to XML Converter",
		Description: "Convert JSON data to XML.",
		URL:         "/tools/json-to-xml",
		Icon:        "bi bi-file-earmark-code",
		Category:    "other",
	},
	{
		Name:        "JSON to CSV Converter",
		Description: "Convert JSON data to CSV.",
		URL:         "/tools/json-to-csv",
		Icon:        "bi bi-file-earmark-spreadsheet",
		Category:    "other",
	},
	{
		Name:        "JSON to TOML Converter",
		Description: "Convert JSON data to TOML.",
		URL:         "/tools/json-to-toml",
		Icon:        "bi bi-file-earmark-code",
		Category:    "other",
	},
	{
		Name:        "YAML to TOML Converter",
		Description: "Convert YAML data to TOML.",
		URL:         "/tools/yaml-to-toml",
		Icon:        "bi bi-file-earmark-code",
		Category:    "other",
	},
	{
		Name:        "Markdown to Word",
		Description: "Convert Markdown to Word documents.",
		URL:         "/tools/markdown-to-word",
		Icon:        "bi bi-file-earmark-word",
		Category:    "other",
	},
	{
		Name:        "Markdown to PDF",
		Description: "Convert Markdown to PDF documents.",
		URL:         "/tools/markdown-to-pdf",
		Icon:        "bi bi-file-earmark-pdf",
		Category:    "other",
	},
	{
		Name:        "HTML Formatter",
		Description: "Format and beautify HTML code.",
		URL:         "/tools/html-formatter",
		Icon:        "bi bi-code-slash",
		Category:    "other",
	},
	{
		Name:        "JavaScript Formatter",
		Description: "Format and beautify JavaScript code.",
		URL:         "/tools/js-formatter",
		Icon:        "bi bi-file-earmark-code",
		Category:    "other",
	},
	{
		Name:        "SQL Formatter",
		Description: "Format and beautify SQL queries.",
		URL:         "/tools/sql-formatter",
		Icon:        "bi bi-database",
		Category:    "other",
	},
	{
		Name:        "CSS Formatter",
		Description: "Format and beautify CSS code.",
		URL:         "/tools/css-formatter",
		Icon:        "bi bi-file-earmark-code",
		Category:    "other",
	},
	{
		Name:        "Crontab Generator",
		Description: "Generate crontab schedules.",
		URL:         "/tools/crontab-generator",
		Icon:        "bi bi-calendar-plus",
		Category:    "other",
	},
	{
		Name:        "Color Format Converter",
		Description: "Convert colors between formats (Hex, RGB, HSL).",
		URL:         "/tools/color-converter",
		Icon:        "bi bi-palette",
		Category:    "other",
	},
	{
		Name:        "cURL Builder",
		Description: "Build cURL commands with an easy interface.",
		URL:         "/tools/curl-builder",
		Icon:        "bi bi-terminal",
		Category:    "other",
	},
	{
		Name:        "Text Statistics",
		Description: "Analyze text for word count, character count, etc.",
		URL:         "/tools/text-stats",
		Icon:        "bi bi-card-text",
		Category:    "other",
	},
	{
		Name:        "Date/Time Converter",
		Description: "Convert dates and times between timezones and formats.",
		URL:         "/tools/datetime-converter",
		Icon:        "bi bi-clock-history",
		Category:    "other",
	},
	{
		Name:        "URL Decoder",
		Description: "Decode URL-encoded strings.",
		URL:         "/tools/url-decoder",
		Icon:        "bi bi-link-45deg",
		Category:    "other",
	},
	{
		Name:        "Git Cheatsheet",
		Description: "Quick reference for Git commands.",
		URL:         "/tools/git-cheatsheet",
		Icon:        "bi bi-git",
		Category:    "cheatsheet",
	},
	{
		Name:        "Linux Cheatsheet",
		Description: "Quick reference for Linux commands.",
		URL:         "/tools/linux-cheatsheet",
		Icon:        "bi bi-terminal-fill",
		Category:    "cheatsheet",
	},
	{
		Name:        "Regex Cheatsheet",
		Description: "Quick reference for regular expressions.",
		URL:         "/tools/regex-cheatsheet",
		Icon:        "bi bi-braces-asterisk",
		Category:    "cheatsheet",
	},
	{
		Name:        "Docker Cheatsheet",
		Description: "Quick reference for Docker commands.",
		URL:         "/tools/docker-cheatsheet",
		Icon:        "bi bi-box-seam",
		Category:    "cheatsheet",
	},
	{
		Name:        "Kubernetes Cheatsheet",
		Description: "Quick reference for Kubernetes (kubectl) commands.",
		URL:         "/tools/kubernetes-cheatsheet",
		Icon:        "bi bi-bounding-box",
		Category:    "cheatsheet",
	},
	{
		Name:        "FFmpeg Cheatsheet",
		Description: "Quick reference for FFmpeg commands.",
		URL:         "/tools/ffmpeg-cheatsheet",
		Icon:        "bi bi-camera-reels",
		Category:    "cheatsheet",
	},
	{
		Name:        "SSH Cheatsheet",
		Description: "Quick reference for SSH commands.",
		URL:         "/tools/ssh-cheatsheet",
		Icon:        "bi bi-terminal",
		Category:    "cheatsheet",
	},
	{
		Name:        "Linux find Cheatsheet",
		Description: "Quick reference for the 'find' command.",
		URL:         "/tools/find-cheatsheet",
		Icon:        "bi bi-search",
		Category:    "cheatsheet",
	},
	{
		Name:        "Nginx Cheatsheet",
		Description: "Quick reference for Nginx configuration.",
		URL:         "/tools/nginx-cheatsheet",
		Icon:        "bi bi-server",
		Category:    "cheatsheet",
	},
	{
		Name:        "HTTP Status Codes",
		Description: "Quick reference for HTTP status codes.",
		URL:         "/tools/http-status-codes",
		Icon:        "bi bi-cloud-slash",
		Category:    "cheatsheet",
	},
	{
		Name:        "File Types & MIME",
		Description: "Quick reference for file types and MIME types.",
		URL:         "/tools/mime-types-cheatsheet",
		Icon:        "bi bi-file-earmark",
		Category:    "cheatsheet",
	},
	{
		Name:        "Vim Cheatsheet",
		Description: "Quick reference for Vim commands.",
		URL:         "/tools/vim-cheatsheet",
		Icon:        "bi bi-keyboard",
		Category:    "cheatsheet",
	},
	{
		Name:        "Curl Cheatsheet",
		Description: "Quick reference for cURL commands.",
		URL:         "/tools/curl-cheatsheet",
		Icon:        "bi bi-terminal",
		Category:    "cheatsheet",
	},
	{
		Name:        "SQL Cheatsheet",
		Description: "Quick reference for SQL commands.",
		URL:         "/tools/sql-cheatsheet",
		Icon:        "bi bi-database",
		Category:    "cheatsheet",
	},
	{
		Name:        "NetCommands Cheatsheet",
		Description: "Quick reference for network commands (ping, traceroute).",
		URL:         "/tools/net-cheatsheet",
		Icon:        "bi bi-reception-4",
		Category:    "cheatsheet",
	},
	{
		Name:        "Base64 Encoder/Decoder",
		Description: "Encode or decode texts to/from Base64 format.",
		URL:         "/tools/base64",
		Icon:        "bi bi-arrow-repeat",
		Category:    "other",
	},
	{
		Name:        "JWT Decoder",
		Description: "Securely decode the content (Header and Payload) of JSON Web Tokens.",
		URL:         "/tools/jwt-decoder",
		Icon:        "bi bi-key-fill",
		Category:    "other",
	},
	{
		Name:        "Hash Generator",
		Description: "Instantly calculate MD5, SHA-1, and SHA-256 hash values of your texts.",
		URL:         "/tools/hash-generator",
		Icon:        "bi bi-fingerprint",
		Category:    "other",
	},
	{
		Name:        "Unix Timestamp Converter",
		Description: "Convert Unix timestamp to human-readable date and vice versa.",
		URL:         "/tools/timestamp-converter",
		Icon:        "bi bi-hourglass-split",
		Category:    "other",
	},
	{
		Name:        "UUID Generator",
		Description: "Generate random and unique UUIDs.",
		URL:         "/tools/uuid-generator",
		Icon:        "bi bi-grip-horizontal",
		Category:    "other",
	},
	{
		Name:        "Regex Tester",
		Description: "Test regular expressions and see matches instantly.",
		URL:         "/tools/regex-tester",
		Icon:        "bi bi-search",
		Category:    "other",
	},
	{
		Name:        "Color Picker / Converter",
		Description: "Convert and select color codes (HEX, RGB, HSL).",
		URL:         "/tools/color-picker",
		Icon:        "bi bi-palette-fill",
		Category:    "other",
	},
	{
		Name:        "Lorem Ipsum Generator",
		Description: "Quickly generate fake text (lorem ipsum).",
		URL:         "/tools/lorem-ipsum",
		Icon:        "bi bi-file-earmark-text-fill",
		Category:    "other",
	},
	{
		Name:        "URL Encoder/Decoder",
		Description: "Encode or decode texts to/from URL format.",
		URL:         "/tools/url-encoder",
		Icon:        "bi bi-link-45deg",
		Category:    "other",
	},
	{
		Name:        "Case Converter",
		Description: "Convert your texts to formats like snake_case, camelCase, PascalCase.",
		URL:         "/tools/case-converter",
		Icon:        "bi bi-letter-case",
		Category:    "other",
	},
	{
		Name:        "HTML/CSS/JS Minifier",
		Description: "Minify and optimize your code.",
		URL:         "/tools/minifier",
		Icon:        "bi bi-file-zip-fill",
		Category:    "other",
	},
	{
		Name:        "Markdown Previewer",
		Description: "Instantly preview your Markdown files.",
		URL:         "/tools/markdown-previewer",
		Icon:        "bi bi-markdown-fill",
		Category:    "other",
	},
	{
		Name:        "Diff Checker",
		Description: "Compare differences between two text or code blocks.",
		URL:         "/tools/diff-checker",
		Icon:        "bi bi-file-diff-fill",
		Category:    "other",
	},
	{
		Name:        "Random String Generator",
		Description: "Generate secure random strings.",
		URL:         "/tools/random-string",
		Icon:        "bi bi-shuffle",
		Category:    "other",
	},
}
